# syntax = edrevo/dockerfile-plus

FROM mcr.microsoft.com/devcontainers/typescript-node:1-18

INCLUDE+ ../Dockerfile.begin

RUN sudo apt update && \
  sudo apt upgrade -y && \
  curl -s https://api.github.com/repos/gitleaks/gitleaks/releases/latest \
  | grep "browser_download_url.*darwin_arm64.tar.gz" \
  | cut -d : -f 2,3 \
  | tr -d '\"' \
  | wget -qi - && \
  tar -xzf *darwin_arm64.tar.gz && \
  sudo mv gitleaks /usr/local/bin/ && \
  sudo rm *.tar.gz

INCLUDE+ ../Dockerfile.end
