apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '21'
spec:
  destination:
    namespace: external-secrets
    server: https://kubernetes.default.svc
  project: cluster
  source:
    chart: external-secrets
    helm:
      parameters:
        - name: installCRDs
          value: 'false'
    repoURL: https://charts.external-secrets.io
    targetRevision: 0.12.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
