---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: level7-application
spec:
  interval: 20s
  dependsOn:
    - name: level6-application-core
  path: './k8s/.../application'
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks: []
