---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: level3-insfrastructure
spec:
  interval: 20s
  dependsOn:
    - name: level2-insfrastructure-core
  path: './k8s/flux-playground/traefik-minikube-vault-helm/infrastructure'
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: external-secrets.io/v1beta1
      kind: SecretStore
      name: store
      namespace: apps
