---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: level1-insfrastructure
spec:
  interval: 20s
  dependsOn:
    - name: flux-system
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./k8s/flux-playground/flux-multi-tenant-replicate/clusters/${cluster}/infrastructure
  healthChecks:
    - apiVersion: source.toolkit.fluxcd.io/v1
      kind: HelmChart
      name: replicator-replicator
      namespace: replicator
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: replicator
      namespace: replicator
    - apiVersion: apps/v1
      kind: Deployment
      name: replicator-kubernetes-replicator
      namespace: replicator
