---
apiVersion: notification.toolkit.fluxcd.io/v1
kind: Receiver
metadata:
  name: apps
spec:
  type: dockerhub
  secretRef:
    name: webhook-docker-token
  resources:
    - kind: ImageRepository
      name: flux-automated
    - kind: ImageRepository
      name: myproject-automated
    - kind: ImageUpdateAutomation
      apiVersion: image.toolkit.fluxcd.io/v1beta2
      name: flux-system
---
apiVersion: notification.toolkit.fluxcd.io/v1
kind: Receiver
metadata:
  name: git
spec:
  type: dockerhub
  secretRef:
    name: webhook-git-token
  resources:
    - apiVersion: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      name: flux-system
    - apiVersion: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      name: level1-crds
    - apiVersion: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      name: level2-insfrastructure-core
    - apiVersion: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      name: level3-insfrastructure
    - apiVersion: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      name: level4-application
