apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flux
spec:
  chart:
    spec:
      chart: generic-chart
      sourceRef:
        kind: HelmRepository
        name: generic-helm
        namespace: apps
      version: 1.0.1
  interval: 5m
  values:
    vault:
      enabled: true
      secretStoreKind: ClusterSecretStore
      secretStore: store

    secrets:
      webhook-git-token:
        enabled: true
        secretName: webhook-git-token
        secretConfig:
          cluster:
            token: flux.notification.git-token
      webhook-docker-token:
        enabled: true
        secretName: webhook-docker-token
        secretConfig:
          cluster:
            token: flux.notification.docker-token

    apps:
      curl:
        deployment:
          enabled: true
          image:
            registry: curlimages
          container:
            command: ['tail', '-f', '/dev/null']
