apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: foo
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '-1'
spec:
  description: Everything related to foo
  destinations:
    - namespace: 'foo'
      server: '*'
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceRepos:
    - '*'
