---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: fake-external-secret
spec:
  refreshInterval: '30s'
  secretStoreRef:
    name: fake
    kind: SecretStore
  target:
    name: fake-secret
    template:
      engineVersion: v2
      data:
        # multiline string
        config: |
          datasources:
          - name: Graphite
            type: graphite
            access: proxy
            url: {{ .url | replace "postgres://" "postgresql://" }}
            user: "{{ .username }}"
        # using replace function to rewrite secret
        connection: '{{ .url | replace "postgres://" "postgresql://" }}'
        computed: '{{ (.complex | fromJson).test.password }}'
        url: '{{ .url }}'
  data:
    - secretKey: username
      remoteRef:
        key: user
    - secretKey: complex
      remoteRef:
        key: secrets
  dataFrom:
    - extract:
        key: database
