---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: level3-vault
spec:
  interval: 20s
  dependsOn:
    - name: level2-vault-core
  path: './k8s/.../vault'
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks: []
