---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test-fake-secret-public-api
spec:
  refreshInterval: '30s'
  secretStoreRef:
    name: fake-structured
    kind: ClusterSecretStore
  target:
    name: test-secret-public-api
    template:
      engineVersion: v2
      metadata:
        annotations:
          reloader.stakater.com/match: 'true'
        labels:
          application: public-api
      data:
        # full data
        full: '{{ . }}'
        admin_password: '{{ (.data | fromJson).admin_password.test }}'
        db_password: '{{ (.db | fromJson).test }}'
        third_party_first_id: '{{ (.data | fromJson).third_party_first_id.test }}'
        third_party_first_key: '{{ (.data | fromJson).third_party_first_key.test }}'
        third_party_two_id: '{{ (.data | fromJson).third_party_two_id.test }}'
        third_party_two_key: '{{ (.data | fromJson).third_party_two_key.test }}'
  data:
    - secretKey: data
      remoteRef:
        key: secrets
    # Example using property
    - secretKey: db
      remoteRef:
        key: secrets
        property: db_password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test-fake-secret-internal-api
spec:
  refreshInterval: '30s'
  secretStoreRef:
    name: fake-structured
    kind: ClusterSecretStore
  target:
    name: test-secret-internal-api
    template:
      engineVersion: v2
      metadata:
        annotations:
          reloader.stakater.com/match: 'true'
        labels:
          application: internal-api
      data:
        admin_password: '{{ (.data | fromJson).admin_password.test }}'
  data:
    - secretKey: data
      remoteRef:
        key: secrets
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test-fake-secret-web-ui
spec:
  refreshInterval: '30s'
  secretStoreRef:
    name: fake-structured
    kind: ClusterSecretStore
  target:
    name: test-secret-web-ui
    template:
      engineVersion: v2
      metadata:
        annotations:
          reloader.stakater.com/match: 'true'
        labels:
          application: web-ui
      data:
        third_party_first_id: '{{ (.data | fromJson).third_party_first_id.test }}'
        third_party_first_key: '{{ (.data | fromJson).third_party_first_key.test }}'
  data:
    - secretKey: data
      remoteRef:
        key: secrets
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: prod-fake-secret-public-api
spec:
  refreshInterval: '30s'
  secretStoreRef:
    name: fake-structured
    kind: ClusterSecretStore
  target:
    name: prod-secret-public-api
    template:
      engineVersion: v2
      metadata:
        annotations:
          reloader.stakater.com/match: 'true'
        labels:
          application: public-api
      data:
        admin_password: '{{ (.data | fromJson).admin_password.prod }}'
        db_password: '{{ (.data | fromJson).db_password.prod }}'
        third_party_first_id: '{{ (.data | fromJson).third_party_first_id.prod }}'
        third_party_first_key: '{{ (.data | fromJson).third_party_first_key.prod }}'
        third_party_two_id: '{{ (.data | fromJson).third_party_two_id.prod }}'
        third_party_two_key: '{{ (.data | fromJson).third_party_two_key.prod }}'
  data:
    - secretKey: data
      remoteRef:
        key: secrets
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: prod-fake-secret-internal-api
spec:
  refreshInterval: '30s'
  secretStoreRef:
    name: fake-structured
    kind: ClusterSecretStore
  target:
    name: prod-secret-internal-api
    template:
      engineVersion: v2
      metadata:
        annotations:
          reloader.stakater.com/match: 'true'
        labels:
          application: internal-api
      data:
        admin_password: '{{ (.data | fromJson).admin_password.prod }}'
  data:
    - secretKey: data
      remoteRef:
        key: secrets
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: prod-fake-secret-web-ui
spec:
  refreshInterval: '30s'
  secretStoreRef:
    name: fake-structured
    kind: ClusterSecretStore
  target:
    name: prod-secret-web-ui
    template:
      engineVersion: v2
      metadata:
        annotations:
          reloader.stakater.com/match: 'true'
        labels:
          application: web-ui
      data:
        third_party_first_id: '{{ (.data | fromJson).third_party_first_id.prod }}'
        third_party_first_key: '{{ (.data | fromJson).third_party_first_key.prod }}'
  data:
    - secretKey: data
      remoteRef:
        key: secrets
