---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-cluster-secret-store
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-west-1 # PUT THE RIGHT REGION
      role: arn:aws:iam::<AWS ACCOUNT ID>:role/external-secrets-project-test # PUT A VALID IAM ROLE
      auth:
        secretRef:
          accessKeyIDSecretRef:
            namespace: external-secrets
            name: awssm-secret
            key: access-key
          secretAccessKeySecretRef:
            namespace: external-secrets
            name: awssm-secret
            key: secret-access-key
  conditions:
    - namespaceSelector:
        matchLabels:
          aws-secret/cluster-store: access-cluster-store
