---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-cluster-secret-store
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-west-1 # PUT THE RIGHT REGION
      role: iam-role # PUT A VALID IAM ROLE
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: awssm-secret
            key: access-key
          secretAccessKeySecretRef:
            name: awssm-secret
            key: secret-access-key
  conditions:
    - namespaceSelector:
        matchLabels:
          aws-secret/cluster-store: access-cluster-store
