apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../flux/base/flux-system/2.4.0
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: source-controller
      namespace: flux-system
    patch: |-
      - op: add
        path: /spec/template/spec/volumes/-
        value:
          name: certificates
          configMap:
            name: certificates
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/-
        value:
          name: certificates
          mountPath: /etc/ssl/certs/ca-certificates.crt
          subPath: ca-certificates.crt
      # - op: add
      #   path: /spec/template/spec/containers/0/args/-
      #   value: --log-level=trace
