apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - ../../../base/flux-system/flux-system
  - config.yaml
patches:
  - target:
      group: kustomize.toolkit.fluxcd.io
      kind: Kustomization
      name: flux-system
    patch: |-
      - op: add
        path: /spec/path
        value: ./k8s/flux-playground/flux-multi-tenant-replicate/clusters/minikube/flux-system
