# Allow everything
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flux-cluster-admin-binding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: flux-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
# # Allow to modify flux resources
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRoleBinding
# metadata:
#   name: flux-edit-default-binding
# subjects:
#   - kind: ServiceAccount
#     name: default
#     namespace: flux-system
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: ClusterRole
#   name: flux-edit-flux-system

# # Allow to create namespaces
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRole
# metadata:
#   name: namespace-creator
# rules:
#   - apiGroups: ['']
#     resources: ['namespaces']
#     verbs: ['create', 'get', 'list', 'watch', 'patch', 'update']
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRoleBinding
# metadata:
#   name: namespace-creator-binding
# subjects:
#   - kind: ServiceAccount
#     name: default
#     namespace: flux-system
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: ClusterRole
#   name: namespace-creator

# # Allow handling service accounts / role bindings
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRole
# metadata:
#   name: service-account-editor
# rules:
#   - apiGroups: ['', 'rbac.authorization.k8s.io']
#     resources: ['serviceaccounts', 'rolebindings']
#     verbs: ['create', 'get', 'list', 'watch', 'patch', 'update']
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRoleBinding
# metadata:
#   name: service-account-editor-binding
# subjects:
#   - kind: ServiceAccount
#     name: default
#     namespace: flux-system
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: ClusterRole
#   name: service-account-editor
