{{- range $appName, $currentApp := .Values.apps }}
  {{- if $currentApp.deployment }}
    {{- if $currentApp.deployment.enabled }}
      {{- $deployment := $currentApp.deployment }}
      {{- include "chart.external-secrets.generate" (dict "context" $ "appName" $appName "deployment" $deployment)  }}
    {{- end }}
  {{- end }}
{{- end }}
