{{- range $appName, $currentApp := .Values.apps }}
  {{- if $currentApp.deployment }}
    {{- if $currentApp.deployment.enabled }}
      {{- if $currentApp.deployment.vault }}
        {{- include "chart.external-secrets.generate" (dict "context" $ "appName" $appName "config" $currentApp.deployment.vault)  }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}

{{- range $secretName, $currentSecret := .Values.secrets }}
  {{- if $currentSecret.enabled }}
    {{- include "chart.external-secrets.generate" (dict "context" $ "appName" $secretName "config" $currentSecret)  }}
  {{- end }}
{{- end }}
