apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: playground-traefik-minikube
resources:
  - ../../../flux/base/application/nginx
  - config.yaml
  - ingress.yaml
patches:
  - path: deployment-patch.yaml
