---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: level1-crds
spec:
  interval: 20s
  dependsOn:
    - name: flux-system
  path: './k8s/.../crds'
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks: []
