---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: home
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`nginx-kind.localhost`) && Path(`/`)
      services:
        - kind: Service
          name: nginx
          port: 80
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: home-tls
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - web
    # - websecure
  routes:
    - kind: Rule
      match: Host(`nginx-kind-tls.localhost`) && Path(`/`)
      services:
        - kind: Service
          name: nginx
          port: 80
