---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: level2-vault-core
spec:
  interval: 20s
  dependsOn:
    - name: level1-crds
  path: './k8s/flux-playground/external-secrets/vault-core'
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    # replicator
    - apiVersion: source.toolkit.fluxcd.io/v1
      kind: HelmRepository
      name: kubernetes-replicator
      namespace: replicator
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: replicator
      namespace: replicator
    # reloader
    - apiVersion: source.toolkit.fluxcd.io/v1
      kind: HelmRepository
      name: reloader
      namespace: reloader
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: reloader
      namespace: reloader
    # external-secrets
    - apiVersion: source.toolkit.fluxcd.io/v1
      kind: HelmRepository
      name: external-secrets-io
      namespace: external-secrets
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: external-secrets
      namespace: external-secrets
