---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: replicator
spec:
  interval: 5m
  chart:
    spec:
      chart: kubernetes-replicator
      version: 2.11.0
      sourceRef:
        kind: HelmRepository
        name: kubernetes-replicator
        namespace: replicator
  # https://github.com/mittwald/kubernetes-replicator/blob/master/deploy/helm-chart/kubernetes-replicator/values.yaml
  values: {}
