---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external
spec:
  refreshInterval: '30s'
  secretStoreRef:
    name: aws-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: external
  dataFrom:
    - extract:
        key: external-secrets-project-test-external
