---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: level6-application-core
spec:
  interval: 20s
  dependsOn:
    - name: level5-insfrastructure
  path: './k8s/flux-playground/external-secrets/application-core'
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks: []
