apiVersion: notification.toolkit.fluxcd.io/v1
kind: Receiver
metadata:
  name: apps
spec:
  type: dockerhub
  secretRef:
    name: webhook-token
  resources:
    - kind: ImageRepository
      name: flux-automated
    - kind: ImageRepository
      name: myproject-automated
    - kind: ImageUpdateAutomation
      apiVersion: image.toolkit.fluxcd.io/v1beta2
      name: flux-system
