---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: level1-insfrastructure-core
spec:
  healthChecks:
    - apiVersion: source.toolkit.fluxcd.io/v1
      kind: HelmRepository
      name: kubernetes-replicator
      namespace: replicator
