---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: ingress-nginx-controller
      namespace: ingress-nginx
    - apiVersion: source.toolkit.fluxcd.io/v1
      kind: HelmRepository
      name: traefik
      namespace: playground-traefik-kind
    - apiVersion: source.toolkit.fluxcd.io/v1
      kind: HelmChart
      name: playground-traefik-kind-traefik
      namespace: playground-traefik-kind
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: traefik
      namespace: playground-traefik-kind
    - apiVersion: apps/v1
      kind: DaemonSet
      name: traefik
      namespace: playground-traefik-kind
    - apiVersion: traefik.io/v1alpha1
      kind: IngressRoute
      name: traefik-dashboard
      namespace: playground-traefik-kind
    - apiVersion: apps/v1
      kind: Deployment
      name: nginx
      namespace: playground-traefik-kind
    - apiVersion: apps/v1
      kind: Deployment
      name: whoami
      namespace: playground-traefik-kind
    - apiVersion: apps/v1
      kind: Deployment
      name: podinfo
      namespace: playground-traefik-kind
