---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test-fake-secret-public-api
spec:
  refreshInterval: '30s'
  secretStoreRef:
    name: fake-config-templated
    kind: ClusterSecretStore
  target:
    name: test-secret-public-api
    template:
      engineVersion: v2
      metadata:
        annotations:
          reloader.stakater.com/match: 'true'
        labels:
          application: public-api
      templateFrom:
        - target: Data
          configMap:
            name: secrets-config
            items:
              - key: api
                templateAs: KeysAndValues
        - target: Annotations
          configMap:
            name: secrets-config
            items:
              - key: annotations
                templateAs: KeysAndValues
  data:
    - secretKey: data
      remoteRef:
        key: secrets
    # Optionally split them into categories:
    - secretKey: api
      remoteRef:
        key: api
    - secretKey: database
      remoteRef:
        key: database
    - secretKey: thirdParty
      remoteRef:
        key: thirdParty
