apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: replicator
resources:
  - ../../../../flux/base/helm-repositories-namespaced/kubernetes-replicator
  - ../../../../flux/base/infrastructure-namespaced/kubernetes-replicator
