---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: reloader
spec:
  interval: 5m
  chart:
    spec:
      chart: reloader
      version: 1.1.0
      sourceRef:
        kind: HelmRepository
        name: reloader
        namespace: flux-system
  # https://github.com/stakater/Reloader/blob/master/deployments/kubernetes/chart/reloader/values.yaml
  values: {}
