---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: level2-tenant
spec:
  interval: 20s
  dependsOn:
    - name: level1-insfrastructure
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./k8s/flux-playground/flux-multi-tenant-replicate/clusters/${cluster}/tenant
  healthChecks: []
