---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: level2-insfrastructure
spec:
  interval: 20s
  dependsOn:
    - name: level1-insfrastructure-core
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks: []
