---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: level2-insfrastructure
spec:
  healthChecks:
    - apiVersion: source.toolkit.fluxcd.io/v1
      kind: HelmChart
      name: replicator-replicator
      namespace: replicator
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: replicator
      namespace: replicator
    - apiVersion: apps/v1
      kind: Deployment
      name: replicator-kubernetes-replicator
      namespace: replicator
