#! /bin/sh

cd "$(dirname "$(readlink -f "$0")")" || {
  echo "Unable to go to parent folder of $0" >&2
  exit 1
}

tenants_base_path=$(jq -r '.tenant_base_path' <tenants.json)

for tenant_index in $(seq 0 1 $(($(jq '.tenants | length' <tenants.json) - 1))); do
  tenant_info=$(jq '.tenants['"$tenant_index"']' <tenants.json)
  tenant_name="$(echo "$tenant_info" | jq -r '.name')"
  tenant_namespace="$(echo "$tenant_info" | jq -r '.namespace')"
  tenant_git_url="$(echo "$tenant_info" | jq -r '.git_url')"
  tenant_git_path="$(echo "$tenant_info" | jq -r '.git_path')"
  tenant_namespaces="$(echo "$tenant_info" | jq -r '.extra_namespaces[]')"

  echo "Treating tenant $tenant_name..."

  tenant_base_path="$tenants_base_path/$tenant_namespace"
  echo "  - Adding definition to $tenant_base_path"
  mkdir -p "$tenant_base_path"
  echo "# Automatically generated by $0" >"$tenant_base_path"/sync.yaml
  flux create source git --secret-ref flux-system "$tenant_name" --namespace="$tenant_namespace" --url="$tenant_git_url" --branch=main --export | yq >>"$tenant_base_path"/sync.yaml
  flux create kustomization --prune --path to-override "$tenant_name" --namespace="$tenant_namespace" --service-account="$tenant_name" --source=GitRepository/"$tenant_name" --export | yq >>"$tenant_base_path"/sync.yaml
  echo "# Automatically generated by $0" >"$tenant_base_path"/rbac.yaml
  flux create tenant "$tenant_name" --with-namespace="$tenant_namespace" --export | yq >>"$tenant_base_path"/rbac.yaml
  cat <<EOM >"$tenant_base_path"/kustomization.yaml
# Automatically generated by $0
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: $tenant_namespace
resources:
  - rbac.yaml
  - sync.yaml
EOM

  for cluster_index in $(seq 0 1 $(($(jq '.clusters | length' <tenants.json) - 1))); do
    cluster_info=$(jq '.clusters['"$cluster_index"']' <tenants.json)
    cluster_name="$(echo "$cluster_info" | jq -r '.name')"
    cluster_path="$(echo "$cluster_info" | jq -r '.path')"
    cluster_git_branch="$(echo "$cluster_info" | jq -r '.git_branch // "main"')"
    cluster_tenant_git_url="$(echo "$cluster_info" | jq -r '.git_url // "'"$tenant_git_url"'"')"
    tenant_namespaces="$(echo "$tenant_info" | jq -r '[ .extra_namespaces, .extra_cluster_namespaces.["'"$cluster_name"'"] ] | flatten | reduce .[] as $a ([]; if ($a != null) then . += [$a] else . end) | .[]')"
    tenant_cluster_path="${cluster_path}/tenant/${tenant_namespace}"
    echo "  - Adding it to cluster $cluster_name at $tenant_cluster_path..."
    mkdir -p "$tenant_cluster_path"
    kustomization_relative_path="$(realpath --relative-to="$tenant_cluster_path" "$tenant_base_path")"
    kustomization_git_path="$(export cluster_name="${cluster_name}" && echo "$tenant_git_path" | envsubst '\${cluster_name}')"
    cat <<EOM >"$tenant_cluster_path"/kustomization.yaml
# Automatically generated by $0
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - $kustomization_relative_path
patches:
  - target:
      group: kustomize.toolkit.fluxcd.io
      version: v1
      kind: Kustomization
      name: $tenant_name
    patch: |-
      - op: add
        path: /spec/path
        value: $kustomization_git_path
  - target:
      group: source.toolkit.fluxcd.io
      version: v1
      kind: GitRepository
      name: $tenant_name
    patch: |-
      - op: replace
        path: /spec/url
        value: $cluster_tenant_git_url
      - op: replace
        path: /spec/ref/branch
        value: $cluster_git_branch
EOM
    if [ -n "$tenant_namespaces" ]; then
      mkdir -p "${tenant_cluster_path}-namespaces"
      cat <<EOM >"${tenant_cluster_path}-namespaces"/kustomization.yaml
# Automatically generated by $0
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - rbac.yaml
patches:
  # You need to give access to the tenant for each of its namespace
EOM
      echo "# Automatically generated by $0" >"${tenant_cluster_path}-namespaces"/rbac.yaml
      for namespace in $tenant_namespaces; do
        cat <<EOM >>"${tenant_cluster_path}-namespaces"/kustomization.yaml
  - target:
      kind: RoleBinding
      name: ${tenant_name}-reconciler
      namespace: $namespace
    patch: |-
      - op: add
        path: /subjects/-
        value:
          kind: ServiceAccount
          name: $tenant_name
          namespace: $tenant_namespace
EOM
        flux create tenant "$tenant_name" --with-namespace="$namespace" --export | yq >>"${tenant_cluster_path}-namespaces"/rbac.yaml
      done
    fi
  done
done
