apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-secrets
resources:
  - ../../infrastructure/external-secrets
patches:
  - target:
      group: helm.toolkit.fluxcd.io
      kind: HelmRelease
      name: external-secrets
    patch: |-
      - op: replace
        path: /spec/chart/spec/sourceRef/namespace
        value: external-secrets
