apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - ../../../../flux/base/image-repositories/flux-automated
  - ../../../../flux/base/image-repositories/myproject-automated
  - policy.yaml
  - update.yaml
