apiVersion: v1
kind: Service
metadata:
  labels:
    app: podinfo
  name: podinfo
spec:
  ports:
    - name: podinfo
      port: 9898
      protocol: TCP
      targetPort: podinfo
  selector:
    app: podinfo
  type: ClusterIP
status:
  loadBalancer: {}
