---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: store
spec:
  provider:
    fake:
      data:
        - key: application
          value: |
            {
              "api": {
                "admin": {
                  "password": "change-that-password"
                }
              }
            }
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: store
spec:
  provider:
    fake:
      data:
        - key: cluster
          value: |
            {
              "flux": {
                "notification": {
                  "token": "1a3fb2143739a7fc1508381991e6e024b45df58d"
                }
              }
            }
  conditions:
    - namespaces:
        - flux-system
