---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: store
spec:
  provider:
    fake:
      data:
        - key: application
          value: |
            {
              "api": {
                "admin": {
                  "password": "change-that-password"
                }
              }
            }
---
# To generate a token: head -c 12 /dev/urandom | shasum | cut -d ' ' -f1
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: store
spec:
  provider:
    fake:
      data:
        - key: cluster
          value: |
            {
              "flux": {
                "notification": {
                  "docker-token": "1a3fb2143739a7fc1508381991e6e024b45df58d",
                  "git-token": "79f3525ccb58f876fa7334ea6d767dff8e375042"
                }
              }
            }
  conditions:
    - namespaces:
        - flux-system
