apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: store
spec:
  provider:
    fake:
      data:
        - key: application
          value: |
            {
              "api": {
                "admin": {
                  "password": "change-that-password"
                }
              }
            }
