apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik
resources:
  - ../../../../flux/base/helm-repositories-namespaced/traefik
  - ../../../../flux/base/infrastructure-namespaced/traefik-minikube
