apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: reloader
resources:
  - ../../../../flux/base/helm-repositories-namespaced/reloader
  - ../../../../flux/base/infrastructure-namespaced/reloader
