apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: replicator
resources:
  - namespace.yaml
  - ../../../../../../flux/base/helm-repositories/kubernetes-replicator
  - ../../../../../../flux/base/infrastructure/kubernetes-replicator
  - rbac.yaml
patches:
  - path: releases-patch.yaml
