---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: replicator-default-cluster-admin
subjects:
  - kind: ServiceAccount
    name: default
    namespace: replicator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: Role
# metadata:
#   name: replicator
#   namespace: replicator
# rules:
#   - apiGroups: ['']
#     resources: ['namespaces', 'configmaps', 'secrets', 'serviceaccounts']
#     verbs: ['get', 'watch', 'list', 'create', 'update', 'patch', 'delete', 'describe']
#   - apiGroups: ['apps']
#     resources: ['deployments']
#     verbs: ['get', 'watch', 'list', 'create', 'update', 'patch', 'delete', 'describe']
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: RoleBinding
# metadata:
#   name: replicator-binding
#   namespace: replicator
# subjects:
#   - kind: ServiceAccount
#     name: default
#     namespace: replicator
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: Role
#   name: replicator
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRole
# metadata:
#   name: replicator
# rules:
#   - apiGroups: ['rbac.authorization.k8s.io']
#     resources: ['clusterroles', 'clusterrolebindings']
#     verbs: ['get', 'watch', 'list', 'create', 'update', 'patch', 'delete', 'describe']
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRoleBinding
# metadata:
#   name: replicator-binding
# subjects:
#   - kind: ServiceAccount
#     name: default
#     namespace: replicator
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: ClusterRole
#   name: replicator
