apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: replicator
resources:
  - ../../infrastructure/kubernetes-replicator
patches:
  - target:
      group: helm.toolkit.fluxcd.io
      kind: HelmRelease
      name: replicator
    patch: |-
      - op: replace
        path: /spec/chart/spec/sourceRef/namespace
        value: replicator
