apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: # manifests generated during bootstrap
  - ../../../../flux/base/flux-system/customized
  - gotk-sync.yaml
patches:
  - target:
      group: source.toolkit.fluxcd.io
      version: v1
      kind: GitRepository
      name: flux-system
    patch: |-
      - op: replace
        path: /spec/interval
        value: 10s
  # - patch: |
  #     apiVersion: source.toolkit.fluxcd.io/v1
  #     kind: GitRepository
  #     metadata:
  #       name: flux-system
  #       namespace: flux-system
  #     spec:
  #       interval: 10s
  - target:
      group: kustomize.toolkit.fluxcd.io
      version: v1
      kind: Kustomization
      name: flux-system
    patch: |-
      - op: replace
        path: /spec/interval
        value: 10s
