---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-prefix
  namespace: apps
spec:
  stripPrefixRegex:
    regex:
      - '/[^/]+'
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: replace-path-regex
  namespace: apps
spec:
  replacePathRegex:
    regex: ^(.*)bar/three/foo(.*)
    replacement: ${1}four$2
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: add-foo-bar
  namespace: apps
spec:
  addPrefix:
    prefix: /one/foo/bar/two/foo/bar/three/foo/bar
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: custom-header
  namespace: apps
spec:
  headers:
    customRequestHeaders:
      X-Custom-Request-Header: 'Custom Request Header'
    customResponseHeaders:
      X-Custom-Response-Header: 'Custom Response Header'
