apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mychart
  namespace: argocd
spec:
  destination:
    namespace: apps
    server: https://kubernetes.default.svc
  project: cluster
  sources:
    - ref: values
      repoURL: http://gitadmin:v6ccouGZLBogfMn1AzL7@host.local-cluster.internal:3000/gitadmin/local_cluster
      targetRevision: HEAD
    - chart: mychart
      helm:
        valueFiles:
          - $values/k8s/argocd-playground/traefik-minikube-vault-helm/application/mychart/mychart-values.yaml
      repoURL: http://host.local-cluster.internal:8088/
      targetRevision: 1.0.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
