---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test-fake-secret-public-api
spec:
  refreshInterval: '30s'
  secretStoreRef:
    name: fake-flat
    kind: ClusterSecretStore
  target:
    name: test-secret-public-api
  dataFrom:
    - extract:
        key: test-public-api
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test-fake-secret-internal-api
spec:
  refreshInterval: '30s'
  secretStoreRef:
    name: fake-flat
    kind: ClusterSecretStore
  target:
    name: test-secret-internal-api
  dataFrom:
    - extract:
        key: test-internal-api
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test-fake-secret-web-ui
spec:
  refreshInterval: '30s'
  secretStoreRef:
    name: fake-flat
    kind: ClusterSecretStore
  target:
    name: test-secret-web-ui
  dataFrom:
    - extract:
        key: test-web-ui
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: prod-fake-secret-public-api
spec:
  refreshInterval: '30s'
  secretStoreRef:
    name: fake-flat
    kind: ClusterSecretStore
  target:
    name: prod-secret-public-api
  dataFrom:
    - extract:
        key: prod-public-api
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: prod-fake-secret-internal-api
spec:
  refreshInterval: '30s'
  secretStoreRef:
    name: fake-flat
    kind: ClusterSecretStore
  target:
    name: prod-secret-internal-api
  dataFrom:
    - extract:
        key: prod-internal-api
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: prod-fake-secret-web-ui
spec:
  refreshInterval: '30s'
  secretStoreRef:
    name: fake-flat
    kind: ClusterSecretStore
  target:
    name: prod-secret-web-ui
  dataFrom:
    - extract:
        key: prod-web-ui
