---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: level4-application
spec:
  interval: 20s
  dependsOn:
    - name: level3-insfrastructure
  path: './k8s/flux-playground/traefik-minikube-vault-helm/application'
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: apps
      namespace: apps
