---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: level4-application
spec:
  interval: 10m0s
  dependsOn:
    - name: level3-insfrastructure
  path: './k8s/flux-playground/traefik-minikube-vault-helm/application'
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: apps
      namespace: apps
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: flux
      namespace: flux-system
    - apiVersion: notification.toolkit.fluxcd.io/v1
      kind: Receiver
      name: git
      namespace: flux-system
    - apiVersion: notification.toolkit.fluxcd.io/v1
      kind: Receiver
      name: apps
      namespace: flux-system
