apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - ../../../base/flux-system/level2-infrastructure
patches:
  - target:
      kind: Kustomization
    patch: |-
      - op: replace
        path: /spec/path
        value: ./k8s/flux-playground/flux-multi-tenant-replicate/clusters/minikube/infrastructure
