apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: reloader
resources:
  - ../../infrastructure/reloader
patches:
  - target:
      group: helm.toolkit.fluxcd.io
      kind: HelmRelease
      name: reloader
    patch: |-
      - op: replace
        path: /spec/chart/spec/sourceRef/namespace
        value: reloader
