---
apiVersion: v1
kind: Namespace
metadata:
  name: access-cluster-secret-1
  labels:
    fake-secret/cluster-store: access-cluster-store
---
apiVersion: v1
kind: Namespace
metadata:
  name: access-cluster-secret-2
  # It will not work without that
  # labels:
  #   fake-secret/cluster-store: access-cluster-store
---
apiVersion: v1
kind: Namespace
metadata:
  name: access-cluster-secret-extra
  labels:
    fake-secret/cluster-secret: access-cluster-secret
    fake-secret/cluster-store: access-cluster-store
