http:
  services:
    minikube:
      loadBalancer:
        servers:
          - url: 'http://192.168.49.2:80'

  routers:
    # Unfortunately, the replacePathRegex middleware does not work with Host
    minikube:
      entryPoints:
        - web
      rule: Host(`*.minikube.localhost`)
      service: minikube
      middlewares:
        - minikube-remove-last-subdomain

    # So we need to create a middleware for each host
    minikube-traefik:
      entryPoints:
        - web
      rule: Host(`dashboard.traefik.minikube.localhost`)
      service: minikube
      middlewares:
        - minikube-traefik-host
    minikube-whoami:
      entryPoints:
        - web
      rule: Host(`whoami.traefik.minikube.localhost`)
      service: minikube
      middlewares:
        - minikube-whoami-host
    minikube-podinfo:
      entryPoints:
        - web
      rule: Host(`podinfo.traefik.minikube.localhost`)
      service: minikube
      middlewares:
        - minikube-podinfo-host
    minikube-flux-automated:
      entryPoints:
        - web
      rule: Host(`flux-automated.traefik.minikube.localhost`)
      service: minikube
      middlewares:
        - minikube-flux-automated-host
    minikube-flux-webhook:
      entryPoints:
        - web
      rule: Host(`flux-webhook.traefik.minikube.localhost`)
      service: minikube
      middlewares:
        - minikube-flux-webhook-host

    # docker registry webhook to trigger minikube flux
    docker-registry-webhook:
      entryPoints:
        - web
      rule: Host(`traefik`) && PathPrefix(`/hook`)
      service: minikube
      middlewares:
        - minikube-flux-webhook-host
