---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: level4-insfrastructure-core
spec:
  interval: 20s
  dependsOn:
    - name: level3-vault
  path: './k8s/.../infrastructure'
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks: []
